name: Schedule health check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
      

jobs:
  check-health:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service
        uses: Jtalk/url-health-check-action@v3
        with:
          url: https://cx-pokedex-v2.fly.dev
