name: Schedule health check

on:
  schedule:
    - cron: '35 18 * * *'

jobs:
  check-health:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Get the deployed service URL
        id: get-url
        run: |
          URL=$(flyctl status | grep 'Hostname' | awk '{print "https://"$3}')
          echo "deployed_url=$URL" >> $GITHUB_OUTPUT
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Check the deployed service
        uses: Jtalk/url-health-check-action@v3
        with:
          url: ${{ steps.get-url.outputs.deployed_url }}
      - name: Broadcast failure result to Discord
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          text: Scheduled health check failed for ${{ steps.get-url.outputs.deployed_url }}.
          description: ${{ steps.check-health.outputs.summary }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Broadcast success result to Discord
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          text: Scheduled health check passed for ${{ steps.get-url.outputs.deployed_url }}.
          description: ${{ steps.check-health.outputs.summary }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
